# Generated by Django 4.1.3 on 2023-02-27 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_insercion', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(max_length=128)),
                ('distrito_id', models.SmallIntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.persona')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=16, unique=True)),
                ('prioridad', models.IntegerField(choices=[(3, '3ra Edad, Embarazadas, Discapacidad'), (2, 'Clientes corporativos'), (1, 'Clientes personales')], null=True)),
                ('horario_atencion', models.TimeField(default=django.utils.timezone.now)),
                ('espcialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turnero.servicio')),
            ],
            options={
                'db_table': 'atencion',
            },
        ),
    ]
