# Generated by Django 4.1.6 on 2023-02-24 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nro_caja', models.IntegerField()),
                ('fecha_insercion', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(max_length=128)),
                ('distrito_id', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteCola',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.cliente')),
            ],
            options={
                'db_table': 'cliente_cola',
            },
        ),
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cola',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=16)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15, unique=True)),
                ('codigo', models.SmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'estado_cliente',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=32)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField(default=datetime.date(2023, 2, 24))),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'prioridad',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=32)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=15)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=16)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=16)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=16)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo_iso2', models.CharField(max_length=2)),
                ('codigo_iso3', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=16)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'pais',
                'unique_together': {('codigo_iso2', 'codigo_iso3')},
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=24)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.SmallIntegerField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.pais')),
            ],
            options={
                'db_table': 'nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=32)),
                ('activo', models.BooleanField()),
                ('fecha_insercion', models.DateTimeField()),
                ('usuario_insercion', models.CharField(max_length=16)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=16, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.departamento')),
            ],
            options={
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=30)),
                ('generado_por', models.CharField(max_length=15)),
                ('cliente_cola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.clientecola')),
                ('cola_destino', models.ForeignKey(db_column='cola_destino', on_delete=django.db.models.deletion.CASCADE, related_name='cola_destino', to='Turnero.cola')),
                ('cola_inicio', models.ForeignKey(db_column='cola_inicio', on_delete=django.db.models.deletion.CASCADE, related_name='cola_inicio', to='Turnero.cola')),
            ],
            options={
                'db_table': 'derivacion',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais_is',
            field=models.ForeignKey(db_column='pais_is', on_delete=django.db.models.deletion.CASCADE, to='Turnero.pais'),
        ),
        migrations.AddField(
            model_name='cola',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.servicio'),
        ),
        migrations.AddField(
            model_name='clientecola',
            name='cola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.cola'),
        ),
        migrations.AddField(
            model_name='clientecola',
            name='estado',
            field=models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.CASCADE, to='Turnero.estadocliente'),
        ),
        migrations.AddField(
            model_name='clientecola',
            name='prioridad',
            field=models.ForeignKey(db_column='prioridad', on_delete=django.db.models.deletion.CASCADE, to='Turnero.prioridad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.persona'),
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio_atencion', models.TimeField()),
                ('hora_fin_atencion', models.DateTimeField()),
                ('cliente_atendido', models.ForeignKey(db_column='cliente_atendido', on_delete=django.db.models.deletion.CASCADE, to='Turnero.cliente')),
            ],
            options={
                'db_table': 'atencion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Turnero.persona')),
                ('nombre', models.CharField(max_length=16, unique=True)),
                ('clave', models.CharField(max_length=32)),
                ('activo', models.BooleanField()),
                ('persona_id', models.IntegerField()),
                ('fecha_insercion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_usfecha_uso_inicioo', models.DateTimeField()),
                ('fecha_uso_fin', models.DateTimeField(blank=True, null=True)),
                ('arqueo', models.IntegerField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.caja')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.servicio')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnero.usuario')),
            ],
            options={
                'db_table': 'apertura_caja',
            },
        ),
    ]
