# Generated by Django 4.1.3 on 2023-02-25 01:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Turnero', '0002_alter_persona_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='cliente_atendido',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='hora_fin_atencion',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='hora_inicio_atencion',
        ),
        migrations.AddField(
            model_name='atencion',
            name='ci',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='espcialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turnero.servicio'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='horario_atencion',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='atencion',
            name='prioridad',
            field=models.IntegerField(choices=[(3, '3ra Edad, Embarazadas, Discapacidad'), (2, 'Clientes corporativos'), (1, 'Clientes personales')], null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_insercion',
            field=models.DateTimeField(default=datetime.date(2023, 2, 25)),
        ),
    ]
