# Generated by Django 4.1.3 on 2023-02-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnero', '0003_remove_atencion_cliente_atendido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='codigo',
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='ci',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
