# Generated by Django 4.1.3 on 2023-02-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnero', '0004_remove_servicio_activo_remove_servicio_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
