# Generated by Django 4.1.3 on 2023-02-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnero', '0005_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
