# Generated by Django 4.1.3 on 2023-02-26 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnero', '0006_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_insercion',
            field=models.DateTimeField(default=datetime.date(2023, 2, 26)),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[(
                 'M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=20, null=True),
        ),
    ]
