# Generated by Django 4.1.3 on 2023-02-26 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnero', '0007_alter_persona_fecha_insercion_alter_persona_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_modificacion',
        ),

        migrations.RemoveField(
            model_name='persona',
            name='usuario_insercion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario_modificacion',
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_insercion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
